version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  web:
    build: .
    volumes:
      - .:/usr/src/app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=vlaio_prototype.settings
